set(_AMENT_PACKAGE_NAME "lidar_perception")
set(lidar_perception_VERSION "0.1.0")
set(lidar_perception_MAINTAINER "heruonan <ruonan.he@magride.cn>")
set(lidar_perception_BUILD_DEPENDS "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "geometry_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev" "libopencv-dev")
set(lidar_perception_BUILDTOOL_DEPENDS "ament_cmake")
set(lidar_perception_BUILD_EXPORT_DEPENDS "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "geometry_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev" "libopencv-dev")
set(lidar_perception_BUILDTOOL_EXPORT_DEPENDS )
set(lidar_perception_EXEC_DEPENDS "launch" "launch_ros" "robot_state_publisher" "tf2_ros" "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "geometry_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev" "libopencv-dev")
set(lidar_perception_TEST_DEPENDS )
set(lidar_perception_GROUP_DEPENDS )
set(lidar_perception_MEMBER_OF_GROUPS )
set(lidar_perception_DEPRECATED "")
set(lidar_perception_EXPORT_TAGS)
list(APPEND lidar_perception_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
