set(_AMENT_PACKAGE_NAME "sensor_fusion")
set(sensor_fusion_VERSION "0.1.0")
set(sensor_fusion_MAINTAINER "juchunyu <juchunyu@todo.todo>")
set(sensor_fusion_BUILD_DEPENDS "rclcpp" "message_filters" "ros_plc" "std_msgs" "sensor_msgs" "visualization_msgs")
set(sensor_fusion_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(sensor_fusion_BUILD_EXPORT_DEPENDS "rclcpp" "message_filters" "ros_plc" "std_msgs" "sensor_msgs" "visualization_msgs")
set(sensor_fusion_BUILDTOOL_EXPORT_DEPENDS )
set(sensor_fusion_EXEC_DEPENDS "rosidl_default_runtime" "rclcpp" "message_filters" "ros_plc" "std_msgs" "sensor_msgs" "visualization_msgs")
set(sensor_fusion_TEST_DEPENDS "ament_cmake_gtest")
set(sensor_fusion_GROUP_DEPENDS )
set(sensor_fusion_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(sensor_fusion_DEPRECATED "")
set(sensor_fusion_EXPORT_TAGS)
list(APPEND sensor_fusion_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
