set(_AMENT_PACKAGE_NAME "start_all")
set(start_all_VERSION "0.1.0")
set(start_all_MAINTAINER "jj <jj@todo.todo>")
set(start_all_BUILD_DEPENDS )
set(start_all_BUILDTOOL_DEPENDS "ament_cmake")
set(start_all_BUILD_EXPORT_DEPENDS )
set(start_all_BUILDTOOL_EXPORT_DEPENDS )
set(start_all_EXEC_DEPENDS "launch" "launch_ros" "lidar_perception" "ros_plc" "sensor_fusion" "rviz2" "tf2_ros")
set(start_all_TEST_DEPENDS )
set(start_all_GROUP_DEPENDS )
set(start_all_MEMBER_OF_GROUPS )
set(start_all_DEPRECATED "")
set(start_all_EXPORT_TAGS)
list(APPEND start_all_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
