set(_AMENT_PACKAGE_NAME "ros_plc")
set(ros_plc_VERSION "0.1.0")
set(ros_plc_MAINTAINER "why <why@todo.todo>")
set(ros_plc_BUILD_DEPENDS "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev")
set(ros_plc_BUILDTOOL_DEPENDS "ament_cmake" "rosidl_default_generators")
set(ros_plc_BUILD_EXPORT_DEPENDS "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev")
set(ros_plc_BUILDTOOL_EXPORT_DEPENDS )
set(ros_plc_EXEC_DEPENDS "rosidl_default_runtime" "rclcpp" "builtin_interfaces" "sensor_msgs" "std_msgs" "visualization_msgs" "pcl_conversions" "libpcl-all-dev")
set(ros_plc_TEST_DEPENDS )
set(ros_plc_GROUP_DEPENDS )
set(ros_plc_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(ros_plc_DEPRECATED "")
set(ros_plc_EXPORT_TAGS)
list(APPEND ros_plc_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
